using Content.Client._ES.Core;
using Content.Client._ES.Masks;
using Content.Client._ES.Objectives;
using Content.Client._ES.Objectives.Ui;
using Content.Client.Mind;
using Content.Client.Roles;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Auditions.Components;
using Content.Shared._ES.Masks;
using Content.Shared._ES.Objectives.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._ES.Mind.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESCharacterWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly JobSystem _job;
    private readonly ESMaskSystem _mask;
    private readonly MindSystem _mind;
    private readonly ESObjectiveSystem _objective;
    private readonly SpriteSystem _sprite;

    public ESCharacterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _job = _ent.System<JobSystem>();
        _mask = _ent.System<ESMaskSystem>();
        _mind = _ent.System<MindSystem>();
        _objective = _ent.System<ESObjectiveSystem>();
        _sprite = _ent.System<SpriteSystem>();

        ObjectiveHeaderLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-objective-title"));
        Update();
    }

    protected override void Opened()
    {
        base.Opened();

        _mask.OnMaskChanged += OnMaskChanged;
        _objective.OnObjectivesChanged += OnObjectivesChanged;
    }

    public override void Close()
    {
        base.Close();

        _mask.OnMaskChanged -= OnMaskChanged;
        _objective.OnObjectivesChanged -= OnObjectivesChanged;
    }

    private void OnMaskChanged(EntityUid mind, ProtoId<ESMaskPrototype>? mask)
    {
        if (_player.LocalUser is null)
            return;

        if (mind != _mind.GetMind(_player.LocalUser.Value))
            return;

        Update();
    }

    private void OnObjectivesChanged(Entity<ESObjectiveHolderComponent> holder)
    {
        if (_player.LocalUser is null)
            return;

        if (holder != _mind.GetMind(_player.LocalUser.Value))
            return;

        Update();
    }

    public void Update()
    {
        // Oh no!
        if (_player.LocalEntity is not { } localEntity)
            return;

        SelfView.SetEntity(localEntity);

        if (!_mind.TryGetMind(localEntity, out var mind, out var mindComp))
            return;

        if (_ent.TryGetComponent<ESCharacterComponent>(mind, out var character))
            NameLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-name-fmt", ("name", character.Name)));

        if (_job.MindTryGetJob(mind, out var job))
        {
            JobLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-job-fmt", ("name", job.LocalizedName)));
            JobIconTexture.Texture = _sprite.Frame0(_prototype.Index(job.Icon).Icon);
        }

        if (_mask.TryGetMask((mind, mindComp), out var maskId))
        {
            var mask = _prototype.Index(maskId);
            var troupe = _prototype.Index(mask.Troupe);

            MaskLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-mask-fmt",
                ("name", Loc.GetString(mask.Name)),
                ("color", mask.Color)));
            MaskLabel.Margin = new Thickness(16, 0, 0, 0);
            MaskHelpButton.Visible = true;
            var maskTooltip = new Tooltip() { MaxWidth = 250 };
            maskTooltip.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString(mask.Description)));
            MaskHelpButton.TooltipSupplier = _ => maskTooltip;
            MaskHelpButton.TooltipDelay = 0f;

            TroupeLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-troupe-fmt",
                ("name", Loc.GetString(troupe.Name)),
                ("color", troupe.Color)));
            TroupeLabel.Margin = new Thickness(16, 0, 0, 0);

            TroupeHelpButton.Visible = true;
            var troupeTooltip = new Tooltip() { MaxWidth = 350 };
            troupeTooltip.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString(troupe.Description)));
            TroupeHelpButton.TooltipSupplier = _ => troupeTooltip;
            TroupeHelpButton.TooltipDelay = 0f;
        }
        else
        {
            MaskLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-mask-fmt",
                ("name", Loc.GetString("generic-unknown-title")),
                ("color", Color.White)));
            MaskLabel.Margin = new Thickness(0);
            MaskHelpButton.Visible = false;

            TroupeLabel.UnsafeSetMarkup(Loc.GetString("es-character-window-troupe-fmt",
                ("name", Loc.GetString("generic-unknown-title")),
                ("color", Color.Gray)));
            TroupeLabel.Margin = new Thickness(0);
            TroupeHelpButton.Visible = false;
        }

        var info = _mask.GetCharacterInfoBlurb((mind, mindComp));
        var formattedMsg = new FormattedMessage();
        foreach (var msg in info)
        {
            if (info.IndexOf(msg) != 0)
                formattedMsg.PushNewline();
            formattedMsg.AddMessage(msg);
            formattedMsg.PushNewline();
        }
        InfoBlurbText.SetMessage(formattedMsg);
        InfoBlurbText.Visible = !formattedMsg.IsEmpty;

        ObjectivesContainer.Children.Clear();
        foreach (var objective in _objective.GetObjectives(mind))
        {
            var control = new ESObjectiveControl();
            control.SetObjective(objective);
            ObjectivesContainer.AddChild(control);
        }
    }
}
