using Content.Client._ES.Core;
using Content.Client._ES.Masks;
using Content.Client.Roles;
using Content.Shared._ES.Auditions.Components;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ES.Stagehand.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESObservablePlayerButton : Button
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly JobSystem _job;
    private readonly ESMaskSystem _mask;
    private readonly SpriteSystem _sprite;

    public ESObservablePlayerButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _job = _entityManager.System<JobSystem>();
        _mask = _entityManager.System<ESMaskSystem>();
        _sprite = _entityManager.System<SpriteSystem>();

        ToggleMode = true;
    }

    public void SetPlayer(Entity<MindComponent, ESCharacterComponent> ent)
    {
        var (uid, mind, character) = ent;

        var mask = _mask.GetMaskOrNull((uid, mind));
        var troupe = _mask.GetTroupeOrNull((uid, mind));

        NameLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-fmt", ("text", character.Name)));

        if (_job.MindTryGetJob(uid, out var job))
        {
            JobIcon.Texture = _sprite.Frame0(_prototype.Index(job.Icon).Icon);
            JobIcon.ToolTip = job.LocalizedName;
        }

        if (_prototype.TryIndex(mask, out var maskPrototype))
            MaskLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-fmt", ("text", Loc.GetString(maskPrototype.Name))), maskPrototype.Color);

        if (_prototype.TryIndex(troupe, out var troupePrototype))
            TroupeLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-fmt", ("text", Loc.GetString(troupePrototype.Name))), troupePrototype.Color);
    }
}

