using System.Linq;
using Content.Client._ES.Core;
using Content.Client._ES.Masks;
using Content.Client._ES.Objectives;
using Content.Client._ES.Objectives.Ui;
using Content.Client.Roles;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Auditions.Components;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ES.Stagehand.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESStagehandObserveWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly JobSystem _job;
    private readonly ESMaskSystem _mask;
    private readonly ESObjectiveSystem _objective;

    public event Action<EntityUid>? OnWarpButtonPressed;

    public EntityUid? CurrentMind;

    public ESStagehandObserveWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _job = _entityManager.System<JobSystem>();
        _mask = _entityManager.System<ESMaskSystem>();
        _objective = _entityManager.System<ESObjectiveSystem>();

        WarpButton.OnPressed += InvokeWarp;
    }

    public void Update()
    {
        MindsContainer.Children.Clear();

        var minds = new List<Entity<MindComponent, ESCharacterComponent>>();

        var query = _entityManager.EntityQueryEnumerator<ESCharacterComponent, MindComponent>();
        while (query.MoveNext(out var uid, out var character, out var mind))
        {
            if (mind.OriginalOwnerUserId is null)
                continue;

            minds.Add((uid, mind, character));
        }

        var orderedMinds = minds
            .OrderBy(m => _mask.GetTroupeOrNull((m, m.Comp1)))
            .ThenBy(m => m.Comp2.Name);

        var grp = new ButtonGroup();
        foreach (var mind in orderedMinds)
        {
            var button = new ESObservablePlayerButton
            {
                Group = grp,
            };
            button.SetPlayer(mind);
            button.OnPressed += _ =>
            {
                SetInfoPanel(mind);
            };
            MindsContainer.AddChild(button);
        }
    }

    public void SetInfoPanel(Entity<MindComponent, ESCharacterComponent> ent)
    {
        PlayerInfoContainer.Visible = true;

        var (uid, mind, character) = ent;
        CurrentMind = uid;

        var mask = _mask.GetMaskOrNull((uid, mind));
        var troupe = _mask.GetTroupeOrNull((uid, mind));

        NameLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-name-big", ("text", character.Name)));

        if (_job.MindTryGetJob(uid, out var job))
            JobLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-job", ("text", job.LocalizedName)));

        if (_prototype.TryIndex(mask, out var maskPrototype))
            MaskLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-name-big", ("text", Loc.GetString(maskPrototype.Name))), maskPrototype.Color);

        if (_prototype.TryIndex(troupe, out var troupePrototype))
            TroupeLabel.UnsafeSetMarkup(Loc.GetString("es-observe-menu-label-fmt", ("text", Loc.GetString(troupePrototype.Name))), troupePrototype.Color);

        ObjectiveContainer.Children.Clear();
        foreach (var objective in _objective.GetObjectives(uid))
        {
            var ctrl = new ESObjectiveControl();
            ctrl.SetObjective(objective);
            ObjectiveContainer.AddChild(ctrl);
        }
    }

    private void InvokeWarp(BaseButton.ButtonEventArgs obj)
    {
        if (CurrentMind.HasValue)
            OnWarpButtonPressed?.Invoke(CurrentMind.Value);
    }
}

