using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Masks;
using Content.Shared._ES.Nuke;
using Content.Shared._ES.Nuke.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Nuke.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESCryptoNukeConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    private readonly ESSharedMaskSystem _mask;

    public event Action? OnHackButtonPressed;

    public ESCryptoNukeConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mask = _entityManager.System<ESSharedMaskSystem>();

        HackButton.OnPressed += _ => OnHackButtonPressed?.Invoke();

        NavMap.WallColor = Color.Red;
        NavMap.TileColor = Color.Black;
    }

    public void Update(EntityUid owner, ESCryptoNukeConsoleBuiState? state = null)
    {
        if (!_entityManager.TryGetComponent<ESCryptoNukeConsoleComponent>(owner, out var comp))
            return;

        NavMap.MapUid = _entityManager.GetComponent<TransformComponent>(owner).GridUid;
        NavMap.ForceNavMapUpdate();

        if (_player.LocalEntity is { } player)
            HackButton.Visible = _mask.GetTroupeOrNull(player) == ESSharedCryptoNukeSystem.TraitorTroupe;

        if (state != null)
        {
            NavMap.TrackedCoordinates.Clear();
            NavMap.TrackedCoordinates = state.DiskLocations
                .Select(c => (_entityManager.GetCoordinates(c), (true, Color.White)))
                .ToDictionary();

            LocationsLabel.Text = string.Join('\n',
                state.DiskLocations
                    .Select(c => Loc.GetString("es-cryptonuke-ui-label-disk-fmt", ("x", c.X), ("y", c.Y))));

            HackButton.Disabled = !state.CanHack || comp.Compromised;
        }

        HackButton.ToolTip = HackButton.Disabled ? Loc.GetString("es-cryptonuke-ui-button-hack-tooltip") : null;
        CompromisedLabel.Text = Loc.GetString("es-cryptonuke-ui-label-compromised", ("state", comp.Compromised));

        var codes = state?.Codes is { Count: > 0}
            ? string.Join(",", state.Codes)
            : Loc.GetString("es-cryptonuke-ui-label-code-placeholder");
        CodesLabel.Text = Loc.GetString("es-cryptonuke-ui-label-code-header", ("codes", codes));
    }
}
