- type: parallax
  id: Blank

- type: parallax
  id: Default
  layers:
  # ES Start
  # layer1 is not technically needed because its just fullblack but whatever.
  # easier to tweak later this way
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer1.png"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer2.png"
      slowness: 0.996625
      scale: "0.5, 0.5"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer3.png"
      slowness: 0.989375
      scale: "0.5, 0.5"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer4.png"
      slowness: 0.987265625
      scale: "0.5, 0.5"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer5.png"
      slowness: 0.984352
      scale: "0.5, 0.5"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer6.png"
      slowness: 0.980298
      scale: "0.5, 0.5"
  # lq layers are unscaled in order to look better w
  # lores viewport (which auto enables lq parallax)
  layersLQ:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer1.png"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer2.png"
      slowness: 0.996625
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer3.png"
      slowness: 0.989375
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer4.png"
      slowness: 0.987265625
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer5.png"
      slowness: 0.984352
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer6.png"
      slowness: 0.980298
  layersLQUseHQ: false

# Because hyperspace and the menu need their own.
- type: parallax
  id: FastSpace
  layers:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer1.png"
      slowness: 0.5
      scale: "3, 3"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer2.png"
      slowness: 0.25
      scale: "0.5, 0.5"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer3.png"
      slowness: 0.15
      scale: "0.5, 0.5"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer4.png"
      slowness: 0.375
      scale: "0.5, 0.5"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer5.png"
      slowness: 0.125
      scale: "0.5, 0.5"
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer6.png"
      slowness: 0.100
      scale: "0.5, 0.5"
  layersLQ:
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer1.png"
      slowness: 0.5
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer2.png"
      slowness: 0.25
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer3.png"
      slowness: 0.15
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer4.png"
      slowness: 0.375
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer5.png"
      slowness: 0.125
    - texture:
        !type:ImageParallaxTextureSource
        path: "/Textures/_ES/Parallaxes/layer6.png"
      slowness: 0.100
  layersLQUseHQ: false
# ES End
